## Supervise Learning - KNN

In [4]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
#import dataset
ds=pd.read_csv('buy_car.csv')

x=ds.iloc[:,:-1].values #feature (all column except the last 1,meaning of -1)
y=ds.iloc[:,2].values # target/output

In [13]:
ds.head()

Montly Salary  age  Y/N
0           2386   18    0
1           2486   19    0
2           2586   20    0
3           2686   20    0
4           2756   20    0

In [10]:
ds.tail()

Montly Salary  age  Y/N
395          12557   60    1
396          14270   60    1
397          10262   60    1
398           7782   60    0
399          11186   60    1

In [14]:
#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, 
                                                    y, test_size = 0.25,
                                                    random_state = 0)


In [21]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)


(300, 2)
(100, 2)
(300,)


In [26]:
x_train #to see data before scaling

array([[-0.11986558,  0.45721643],
       [-0.84349017, -1.18392566],
       [ 0.21929466,  0.97547182],
       [-0.38082968, -0.40654257],
       [-0.08728385,  0.71634413],
       [ 2.30390443,  1.14822362],
       [-0.73116079, -1.09754976],
       [ 0.53145861,  1.23459952],
       [-0.64179378, -0.49291847],
       [-0.29890991,  0.80272003],
       [-0.80097877, -0.92479796],
       [-0.73395351, -1.01117386],
       [-0.28339481,  0.80272003],
       [-0.88289854, -1.61580516],
       [ 1.42543907,  1.32097542],
       [-0.11303893,  0.19808873],
       [-0.13444978,  0.54359233],
       [-0.81432177, -1.35667746],
       [-0.19371749,  0.37084053],
       [ 1.87041234,  1.14822362],
       [-0.83014717, -0.92479796],
       [-0.07518207,  0.28446463],
       [-0.03949732,  0.37084053],
       [-0.04011793,  0.37084053],
       [ 2.62941137,  1.49372722],
       [-0.34390372, -0.49291847],
       [-0.92882325, -1.61580516],
       [-0.33397405,  0.54359233],
       [ 1.92006068,

In [27]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

sc_x=StandardScaler()

x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

In [28]:
print(x_train) #to see data after scaling

[[-0.11986558  0.45721643]
 [-0.84349017 -1.18392566]
 [ 0.21929466  0.97547182]
 [-0.38082968 -0.40654257]
 [-0.08728385  0.71634413]
 [ 2.30390443  1.14822362]
 [-0.73116079 -1.09754976]
 [ 0.53145861  1.23459952]
 [-0.64179378 -0.49291847]
 [-0.29890991  0.80272003]
 [-0.80097877 -0.92479796]
 [-0.73395351 -1.01117386]
 [-0.28339481  0.80272003]
 [-0.88289854 -1.61580516]
 [ 1.42543907  1.32097542]
 [-0.11303893  0.19808873]
 [-0.13444978  0.54359233]
 [-0.81432177 -1.35667746]
 [-0.19371749  0.37084053]
 [ 1.87041234  1.14822362]
 [-0.83014717 -0.92479796]
 [-0.07518207  0.28446463]
 [-0.03949732  0.37084053]
 [-0.04011793  0.37084053]
 [ 2.62941137  1.49372722]
 [-0.34390372 -0.49291847]
 [-0.92882325 -1.61580516]
 [-0.33397405  0.54359233]
 [ 1.92006068  1.23459952]
 [-0.51053597 -0.32016667]
 [-0.45902582 -0.49291847]
 [ 1.270288    1.66647902]
 [-0.86024648 -1.18392566]
 [-0.24026281  0.45721643]
 [-0.19340719  0.19808873]
 [-0.78391216 -0.83842206]
 [ 0.72446654  0.97547182]
 

In [29]:
#fitting KNN classifier to the training set 
from sklearn.neighbors import KNeighborsClassifier

classifier= KNeighborsClassifier(n_neighbors=5,
                                 metric='minkowski',
                                 p=2) #using Euclidean distance,minkowski,manhattan
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [30]:
#Predict the test set results
y_pred=classifier.predict(x_test)  #classifier is name of the model (reference to above cell)

In [31]:
y_pred

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1], dtype=int64)

In [38]:
#Will a person with salary = 15000 and age = 21 buy the car?
y_pred_new=classifier.predict(sc_x.transform(np.array([[15000,21]])) )

print(y_pred_new)

[1]


In [45]:
#2nd style
salary=int(input("Enter Salary:"))
age=int(input("Enter Age:"))

y_pred_new=classifier.predict(sc_x.transform(np.array([[salary,age]])) )
print(y_pred_new)

Enter Salary:20000
Enter Age:20
[1]


In [47]:
#3rd style
salary=int(input("Enter Salary:"))
age=int(input("Enter Age:"))

y_pred_new=classifier.predict(sc_x.transform(np.array([[salary,age]])) )

if y_pred_new[0]==0:
    print("not buying a car")
else:
    print("will buy a car")


Enter Salary:15000
Enter Age:21
will buy a car


In [48]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score


cm = confusion_matrix(y_test, y_pred)
cm

# only 2 class 1,0 (yes n no)

array([[45,  4],
       [ 3, 48]], dtype=int64)

In [50]:
# Acuracy and precision
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F-score:",f1_score(y_test,y_pred)) 

Accuracy:  0.93
Precision:  0.9230769230769231
Recall:  0.9411764705882353
F-score: 0.9320388349514563


In [52]:
# Acuracy and precision (round number)
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", round(precision_score(y_test, y_pred),4))
print("Recall: ", round(recall_score(y_test, y_pred),4))
print("F-score:",round(f1_score(y_test,y_pred),4))

Accuracy:  0.93
Precision:  0.9231
Recall:  0.9412
F-score: 0.932


In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score


print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))

Accuracy:  0.93
Precision:  0.9230769230769231
Recall:  0.9411764705882353


In [54]:
import pickle #lib to wrap all modelling here into 1 file including parameter (params=minkowski etc)

In [55]:
#pickle.dump(model, open('model.pkl','wb'))

pickle.dump(classifier, open('model.pkl','wb'))

In [ ]:
# to use in new ipynb,
# pickled_model=pickle.load(open('model.pkl','rb'))